### PR TITLE
import/export all fields from the original awesome-selfhosted list, make input/output identical, generate a table of contents and AUTHORS.md, add integration test

### PR DESCRIPTION
**Pull request by nodiscc**
- fixes https://github.com/nodiscc/hecat/issues/6
- fixes https://github.com/nodiscc/hecat/issues/5
- AUTHORS.md export incomplete  https://github.com/nodiscc/hecat/issues/12

### CODE REVIEW

**Comment by nodiscc** [comment]
- [ ] `Content Management Systems (CMS)` section title is not rendered correctly in `related_tags:`

```diff

-_Related: [Content Management Systems](#content-management-systems-cms)_
+_Related: [Content Management Systems](#content-management-systems)_
 ```

**Comment by nodiscc** [comment]
- [ ] generate AUTHORS.md from the source directory git history

**Comment by nodiscc** [comment]
- [ ] render the list of licenses

**Comment by nodiscc** [comment]
- [ ] automate git add/commit/push to the destination directory/repository

**Comment by nodiscc** [comment]
- [ ] fix pylint warnings

**Comment by nodiscc** [comment]
- [ ] build single page HTML and upload to readthedocs

**Review by Rafaelajambeiro — APPROVED** [review]

**Pull request merged**
